### ISSUE TITLE
Outside calls error

### ISSUE THREAD

**Issue by Bioinf-usr** [PharmGKB/PharmCAT#154] opened 2023-09-13 11:55 UTC
* **Do you want to request a *feature* or report a *bug*?**
*bug*

* **What is the current behavior?**
* I am trying to use the latest version pharmcat-2.7.1-all.jar to generate a report. When I'm providing the outside calls, I am getting an error. However, when I'm using the older version (pharmcat-2.3.0-all.jar) it is finishing without any errors.
* _java.lang.UnsupportedOperationException
	at java.base/java.util.AbstractMap.put(AbstractMap.java:209)
	at org.pharmgkb.pharmcat.Pipeline.call(Pipeline.java:287)
	at org.pharmgkb.pharmcat.PharmCAT.main(PharmCAT.java:166)_

* **If the current behavior is a bug, please provide the steps to reproduce and, if possible, your example input data** via a [Gist](https://gist.github.com) or similar.
* /opt/jdk-17.0.7/bin/java -jar pharmcat-2.7.1-all.jar -vcf <vcf> -po test_input.tsv
* Here is my test_input.tsv
          
          CYP2D6  *4/*10  Intermediate Metabolizer
          F5  Reference/Reference Favorable Response
          NUDT15  *1/*1   Normal Metabolizer
          CYP2C19 *38/*38 Normal Metabolizer
          CYP3A5  *1/*1   Normal Metabolizer
          UGT1A1  *1/*6   Intermediate Metabolizer
          SLCO1B1 *1/*37  Normal Function
          DPYD    Reference/c.85T>C (*9A) Normal Metabolizer
          RYR1    Reference/Reference Uncertain Susceptibility
          IFNL3   Reference/Reference Favorable Response
          TPMT    *1/*1   Normal Metabolizer
          CACNA1S Reference/Reference Uncertain Susceptibility
          CYP2C9  *3/*3   Poor Metabolizer
          CYP2B6  *9/*9   Poor Metabolizer

* **Please tell us about your environment:**
  
  - PharmCAT Version: 2.7.1
  - JDK Version: jdk-17.0.7
  - Environment: CentOS

**Comment by whaleyr** [comment] 2023-09-13 19:56
There's a few issues here.

First, we will fix PharmCAT to not crash and give proper warnings about mismatching phenotype values from outside calls.

Second, IFNL3 does not use phenotype values in our system so you don't need to include that in your outside call file.

Third, the phenotype you specified for F5 (`Favorable Response`) is not a recognized phenotype value for PharmCAT. The recognized values are documented [on our phenotypes page](https://pharmcat.org/Phenotypes-List/#f5).

Fourth, I highly recommend not supplying both the diplotype and the phenotype. [As stated in the docs](https://pharmcat.org/using/Outside-Call-Format/) you can do this but if your phenotype doesn't match one of our recognized phenotypes then we will use your phenotype and it will cause a mismatch for recommendations which rely on our recognized phenotype assignments. In this situation, supplying the diplotype calls should be sufficient to get recommendations.

**Comment by Bioinf-usr** [comment] 2023-09-13 20:25
* Thanks a lot for the prompt response. I think I found the issue removing the _IFNL3_ entry from the outside calls files solved the issue. 
* Regarding the phenotypes, I have tried without the phenotypes as well. But, I encountered the same issue. But, the issue got resolved only after removing the _IFNL3_ entry
* Would be great to either issue a warning or ignore the unmatched entries.

**Comment by markwoon** [comment] 2023-09-13 20:50
@Bioinf-usr Can you please attach the original file with the problem?  I'd like to reproduce the bug so that we can improve the error message, and I cannot reproduce it with what you provided.  I'm guessing that it may be some formatting problem.

It would also be helpful if you could provide the full command line and output to help debug things.

What you provided (`/opt/jdk-17.0.7/bin/java -jar pharmcat-2.7.1-all.jar -vcf -po test_input.tsv`) should not work at all because you're not specifying a VCF file.

**Comment by markwoon** [comment] 2023-09-13 20:52
Nevermind, I can reproduce now.

**Comment by markwoon** [comment] 2023-09-13 21:09
I've got a fix for the stacktrace you reported and it will go out in the next PharmCAT release.

**Comment by Bioinf-usr** [comment] 2023-09-21 07:32
Hi,

Just to add another possible bug here. When I tried to provide the _IFNL3_  and _CYP4F2_ calls from outside file. I get the following error.

_java.lang.UnsupportedOperationException
	at java.base/java.util.AbstractMap.put(AbstractMap.java:209)
	at org.pharmgkb.pharmcat.Pipeline.call(Pipeline.java:287)
	at org.pharmgkb.pharmcat.PharmCAT.main(PharmCAT.java:166)_

Here are my calls:

IFNL3   rs12979860 reference (C)/rs12979860 reference (C)
CYP4F2  *1/*3

Am I missing something obvious? When I removed those calls from the file, it runs till the end. Otherwise, it crashes with the error message above.

Please let me know.

Thanks.

**Comment by markwoon** [comment] 2023-09-22 23:47
This should be fixed in [2.8.0](https://github.com/PharmGKB/PharmCAT/releases/tag/v2.8.0).

**Closed by markwoon** 2023-09-22 23:47 UTC
Labels: bug
