### ISSUE TITLE
Allele functions in CYP3A5 do not correspond to dosing guidelines when API is used

### ISSUE THREAD

**Issue by kokyriakidis** [PharmGKB/PharmCAT#29] opened 2020-04-28 13:05 UTC
Hi @whaleyr !

Let's assume I have 2 CYP3A5 alleles: *1 and *9.

When I try to retrieve the function of these alleles with the following command:
```
url_allele <- "https://api.pharmgkb.org/v1/data/guideline/PA166124619/"
  res_allele <- httr::GET(url = url_allele,
                          httr::add_headers('Accept' = 'application/json'),
                          encode = "json")
  #http_status(res_allele)
  res_allele_body <- jsonlite::fromJSON(content(res_allele, as="text"), simplifyVector = FALSE)
```
I get:
```
{
            "id": 1449560766,
            "_label": "*1",
            "function": {
              "@id": "https://pharmgkb.org/ontologyTerm/alleleFunction/haplotypeTags:1445558337",
              "@context": "https://api.pharmgkb.org/jsonld/ontologyTerm.jsonld",
              "id": 1445558337,
              "resource": "Allele Function",
              "term": "Extensive Metabolizer",
              "termId": "haplotypeTags:1445558337"
            }
{
            "id": 1449560774,
            "_label": "*9",
            "function": {
              "@id": "https://pharmgkb.org/ontologyTerm/alleleFunction/haplotypeTags:1448531118",
              "@context": "https://api.pharmgkb.org/jsonld/ontologyTerm.jsonld",
              "id": 1448531118,
              "resource": "Allele Function",
              "term": "Uncertain function",
              "termId": "haplotypeTags:1448531118"
            }
```

Then, when I try to retrieve CPIC dosing guidelines I get an error using:
```
url_guideline <- "https://api.pharmgkb.org/v1/report/guideline/PA166124619/annotations"
  requestBody <- paste0('{"CYP3A5": ["Extensive Metabolizer", "Uncertain function"]}')
  res_guideline <- httr::POST(url = url_guideline,
                              httr::add_headers('Content-Type' = 'application/json'),
                              httr::add_headers('Accept' = 'application/json'),
                              body = requestBody,
                              encode = "json")
  #http_status(res_guideline)
  res_guideline_body <- jsonlite::fromJSON(content(res_guideline, as="text"), simplifyVector = FALSE)
```

Using "Normal function" and "No function" I manage to get some results, but these terms does not exist in the 1st json file (allele -> function):
```
{
  "group": {
    "objCls": "Dosing Guideline Annotation Group",
    "id": "PA166128748",
    "name": "Intermediate Metabolizer",
    "annotations": [
      {
        "id": 1445559092,
        "history": [],
        "markdown": {
          "id": 1447986714,
          "html": "<p>Lower dose-adjusted trough concentrations of tacrolimus and decreased chance of achieving target tacrolimus concentrations.</p>\n"
        },
        "type": {
          "id": 981501925,
          "resource": "Guideline Tags",
          "term": "Implications",
          "termId": "guidelineTags:981501925"
        }
      },
      {
        "id": 1448569713,
        "history": [
          {
            "id": 1448569711,
            "date": "2017-01-31T14:00:32.895-08:00",
            "type": "Create",
            "version": 0
          }
        ],
        "markdown": {
          "id": 1448569712,
          "html": "<p>Intermediate Metabolizer</p>\n"
        },
        "type": {
          "id": 981501926,
          "resource": "Guideline Tags",
          "term": "Metabolizer Status",
          "termId": "guidelineTags:981501926"
        }
      },
      {
        "id": 1445559811,
        "history": [],
        "markdown": {
          "id": 1447986359,
          "html": "<p>An individual carrying one normal function allele and one no function allele (CYP3A5 expresser).</p>\n"
        },
        "type": {
          "id": 981501927,
          "resource": "Guideline Tags",
          "term": "Phenotype (Genotype)",
          "termId": "guidelineTags:981501927"
        }
      },
      {
        "id": 1445559093,
        "history": [],
        "markdown": {
          "id": 1447986715,
          "html": "<p>Increase starting dose 1.5 to 2 times recommended starting dose. Total starting dose should not exceed 0.3mg/kg/day. Use therapeutic drug monitoring to guide dose adjustments.</p>\n<p><em>Further dose adjustments or selection of alternative therapy may be necessary because of other clinical factors (e.g., medication interactions, or hepatic function).</em></p>\n"
        },
        "type": {
          "id": 981501928,
          "resource": "Guideline Tags",
          "term": "Recommendations",
          "termId": "guidelineTags:981501928"
        }
      }
    ],
    "guideline": {
      "objCls": "Guideline Annotation",
      "id": "PA166124619",
      "name": "Annotation of CPIC Guideline for tacrolimus and CYP3A5"
    },
    "rxChangeStatus": {
      "id": 1448602497,
      "resource": "Prescribing Change",
      "term": "Yes",
      "termId": "rxChange:1448602497"
    },
    "strength": {
      "id": 981501930,
      "resource": "Guideline Strength",
      "term": "Strong",
      "termId": "guidelineStrength:981501930"
    }
  }
}
```

So, these 2 json files are not somehow linked. 

I face the same problem with UGT1A1 and Atazanavir.

Any thoughts?

**Comment by whaleyr** [comment] 2020-04-29 02:37
All data for running PharmCAT is packaged with PharmCAT. This is by design.

PharmCAT data does originate from PharmGKB but it is incorrect and unsupported to mix whatever is currently served from PharmGKB with what's included with PharmCAT. The allele definitions and the guideline annotations need to move in tandem and the PharmGKB curators put a lot of work into making sure those all work together correctly before transferring them over to PharmCAT.

We're still waiting on funding to put more curation effort into PharmCAT. We will get a new PharmCAT release with updated guideline annotations and allele definitions eventually but it will take some time. I wish I could be more specific but that's all we can say for now.

**Closed by whaleyr** 2020-04-29 02:37 UTC
