### ISSUE TITLE
Discarded genotype at some positions

### ISSUE THREAD

**Issue by krukanna** [PharmGKB/PharmCAT#128] opened 2023-02-23 10:59 UTC
* **What is the current behavior?**

I've got that issue at some positions:
_Discarded genotype at this position because REF in VCF (A) does not match expected reference (AT)_

My input vcf file looks like below. If no one in the cohort has the variant at that position there is a dot in place of the alternative allele. If anyone had a variant the position looks like e.g chr2:233760233
```
chr10   94949161        .       A       . 
chr10   94942205        .       C       .      
chr19   38499644        .       T       .       
chrX    154532055       .       C       .       
chr2    233760233       .       CAT     CATAT 48396.7 PASS    AC=0,1;AN=2     GT      0/2
```
My question is why the references in your files are different? What version of the reference genome are you using? 
Is it possible to somehow include these positions in the PharmCAT analysis?

* **Please tell us about your environment:**
  - PharmCAT Version: 2.1.2

**Comment by whaleyr** [comment] 2023-02-23 16:42
Are you running your input VCF through [the preprocessor](https://pharmcat.org/using/VCF-Preprocessor/)?

There can be multiple ways to display in-dels and repeats in VCF . The preprocessor normalizes those representations so PharmCAT has a stable, reliable way to match the data to known allele definitions.

**Comment by BinglanLi** [comment] 2023-02-23 17:07
We use GRCh38. As Ryan suggested, this position is an INDEL following the VCF variant specifications >= 4.1. It is like the INDEL in your file at chr2:233760233, which had a reference of CAT, instead of C.

Also, when the preprocessor normalizes the variants, it can normalizes SNVs with an unspecified ALT allele. For INDEL, the preprocessor won’t try to infer an INDEL spanning two basepairs based on only one of the position.

**Comment by krukanna** [comment] 2023-02-24 15:07
Yes, I'm running my input through PharmCAT preprocessor.
These first 4 variants were not detected in my samples, so reference for indel after normalization (in your preprocessing step) it will still be a single basepair. In the final html, these positions are marked as missed and are not taken into account when determining the phenotype.

![image](https://user-images.githubusercontent.com/81685638/221212770-69b72c0a-bf95-43b0-bcfb-6aa5eae7b4a2.png)

**Comment by BinglanLi** [comment] 2023-02-24 17:28
Hi @krukanna, 

INDELs are in general defined as variations whose REF and ALT alleles are of different length. 
```
# an INDEL VCF entry
chr1	4389	.	T	TC,<*>	213.73	.	.	GT:DP:GQ:PL	0/1:23:99:51,0,36,93,92,86
chr10	94949161	.	AT	A	.	PASS	PX=CYP2C9	GT	0/0
```

Additionally, to be specific, PharmCAT uses the genetic information represented by the REF and ALT in an input VCF, not just the position. Your VCF is missing specific REF and ALT information to indicate that these positions are INDELs. The Preprocessor will not infer genotypes for missing INDELs as there is no sufficient information to robustly do so. And since the input VCF does not have the appropriate REF and ALT columns to indicate an INDEL, the genotypes at these positions are not used. 

To resolve the issue, you can fill in the REF and ALT for INDELs in your VCF properly before you pass the file to the Preprocessor or PharmCAT. Alternatively, if you're confident that all other positions are homozygous reference, you can use the `-0` option to ask the Preprocessor to fill up all missing PGx positions as reference (https://pharmcat.org/using/VCF-Preprocessor/). But please note that this function should be used at your own risk.

**Comment by krukanna** [comment] 2023-03-01 11:10
For analysis I use vcf with all examined positions. However, if none of the samples have an identified indel, variant calling process will always return a single allele in REF.
example:
in the photo I sent in an earlier message you can see that the chr10:94949161 variant is Missing, while looking at my vcf both of these positions are present (they have correct coverage and quality):
```
chr10 94949161 . A . . . DP=1346 GT:DP:RGQ 0/0:47:99
chr10 94949162 . T . . . DP=1346 GT:DP:RGQ 0/0:47:99
```
However, this sample is 0/0 in both positions, so there is no indel detected.
I would like PharmCAT not to enter Missing in this position, but AT/AT - this is something he's expecting for in vcf_positions.vcf 

I give one more example - indel where my sample is 0/0 again, but another samples in cohort have detected indels. (so there is something to refer to)
`chr2 233760233 . CAT CATAT,C,CATATAT 51623.40 PASS DP=4774 GT:AD:DP:GQ 0/0:93,0,0,0:93:99`
![image](https://user-images.githubusercontent.com/81685638/222122786-7991a485-e712-4347-bb61-ae2c53c39bba.png)

**Comment by BinglanLi** [comment] 2023-03-01 21:50
@krukanna, this question is more about the variant calling. It will be better addressed by the variant caller tool you used.

I understand what you're saying that there seems to be no INDEL given the two consecutive genomic positions. Nonetheless, it's not a straightforward case to infer so. Here is a hypothetical case:
```
chr10 94949161 . ATT AT . . . GT 0/1
chr10 94949161 . A . . . . GT 0/0
chr10 94949162 . T . . . . GT 0/0
```
Because of cases like this, we cannot generalize and infer an INDEL based on consecutive genomic positions.

**Comment by krukanna** [comment] 2023-03-02 06:29
OK, thank you for your answer.
I have one more idea for solution:
Do you have maybe a representative sample or several that have these selected indels? Then, in the process of joint calling, such samples could be added and genotype for my cohort's samples would be completed.

**Comment by BinglanLi** [comment] 2023-03-04 03:51
Thanks. As an intermediate solution, you can modify the genotypes in the pharmcat_position.vcf file to all 1/1. This sounds like what the joint calling needs. 

I will close the issue for now. Please feel free to reopen the issue and provide any feedback in the future.

**Closed by BinglanLi** 2023-03-04 03:51 UTC

**Comment by bnjvrjnke** [comment] 2023-07-28 05:36
> OK, thank you for your answer. I have one more idea for solution: Do you have maybe a representative sample or several that have these selected indels? Then, in the process of joint calling, such samples could be added and genotype for my cohort's samples would be completed.

I also want to keep confident REF call in the vcf, but the INDEL is still treated as miss in Pharmcat. My idea is keep the confident  homozygous and reduce missing sites. Could you tell me how to joint calling the vcf that can add the pharmcat INDEL to my vcf?

I joint call modified 1/1 pharmcat_position.vcf and my two samples vcf (HaplotypeCaller --output-mode EMIT_ALL_CONFIDENT_SITES --emit-ref-confidence BP_RESOLUTION), then GenomicsDBImport and GenotypeGVCFs. But the GenotypeGVCFs vcf only emit variants sites. If using CombineGVCFs,  all sites will emit but get no genotype (./.).

**Comment by moe1619** [comment] 2023-07-28 10:03
This is overall a wonderful tool. Thank you so much. I am having a similar issue.

**Comment by BinglanLi** [comment] 2023-07-28 17:53
> I also want to keep confident REF call in the vcf, but the INDEL is still treated as miss in Pharmcat. 

Could you please clarify what you meant by indel being treated as missing? PharmCAT doesn't alter your VCF file. It takes whatever that's provided in your VCF. If your VCF doesn't have INDELs, then it's indeed missing.

**Comment by BinglanLi** [comment] 2023-07-28 20:38
> I joint call modified 1/1 pharmcat_position.vcf and my two samples vcf (HaplotypeCaller --output-mode EMIT_ALL_CONFIDENT_SITES --emit-ref-confidence BP_RESOLUTION), then GenomicsDBImport and GenotypeGVCFs. But the GenotypeGVCFs vcf only emit variants sites. If using CombineGVCFs, all sites will emit but get no genotype (./.).

This question will be better addressed by [the GATK forum](https://gatk.broadinstitute.org/hc/en-us/community/topics). You can try out `-L pharmcat_positions.vcf --output-mode EMIT_ALL_ACTIVE_SITES` with `HaplotypeCaller`. But again, the GATK support team should be able to help you with this.

**Comment by bnjvrjnke** [comment] 2023-07-31 02:37
> > I also want to keep confident REF call in the vcf, but the INDEL is still treated as miss in Pharmcat.
> 
> Could you please clarify what you meant by indel being treated as missing? PharmCAT doesn't alter your VCF file. It takes whatever that's provided in your VCF. In other words, PharmCAT only treats an INDEL as missing if it's not present in your VCF.

Thanks for your help. I ran `HaplotypeCaller -L pharmcat_positions.vcf --output-mode EMIT_ALL_ACTIVE_SITES` and used the output to PharmCAT. As krukanna mentioned above:

> However, if none of the samples have an identified indel, variant calling process will always return a single allele in REF.

So the PharmCAT report indel as missing, like this:
<img width="906" alt="image" src="https://github.com/PharmGKB/PharmCAT/assets/44436693/9f10fa09-4e08-487e-b941-da1897802f41">

As krukanna suggest, joint call harmcat_position.vcf (modified to 1/1) with my cohort's samples maybe solve this problem. However, neither GenotypeGVCFs nor CombineGVCFs can add the 0/0 PharmCAT INDEL to my vcf.

**Comment by BinglanLi** [comment] 2023-07-31 18:07
Have you tried the `-0` option in the PharmCAT VCF Preprocessor? However, this SHOULD ONLY BE USED if you are working with whole-genome sequencing data and you are sure your data is reference instead of unreadable/uncallable at those positions.

**Comment by bnjvrjnke** [comment] 2023-08-01 04:52
Yes. I am working with 30× WGS data. I wonder if it is ok to assume this missing INDEL is REF in WGS data? As an intermediate solution, I call the confident sites first `HaplotypeCaller -L pharmcat_positions.vcf --output-mode EMIT_ALL_CONFIDENT_SITES --emit-ref-confidence BP_RESOLUTION`, then convert ALL_CONFIDENT_SITES.vcf to bed and use `bedtools intersect -v -a pharmcat_position.vcf -b ALL_CONFIDENT_SITES.bed` to check whether all PharmCAT sites is missing or not. So far, all harmcat_position.vcf sites of my samples are covered in ALL_CONFIDENT_SITES.

**Comment by bnjvrjnke** [comment] 2023-08-01 04:52
> Have you tried the `-0` option in the PharmCAT VCF Preprocessor? However, this SHOULD ONLY BE USED if you are working with whole-genome sequencing data and you are sure your data is reference instead of unreadable/uncallable at those positions.

Yes. I am working with 30× WGS data. I wonder if it is ok to assume this missing INDEL is REF in WGS data? As an intermediate solution, I call the confident sites first `HaplotypeCaller -L pharmcat_positions.vcf --output-mode EMIT_ALL_CONFIDENT_SITES --emit-ref-confidence BP_RESOLUTION`, then convert ALL_CONFIDENT_SITES.vcf to bed and use `bedtools intersect -v -a pharmcat_position.vcf -b ALL_CONFIDENT_SITES.bed` to check whether all PharmCAT sites is missing or not. So far, all harmcat_position.vcf sites of my samples are covered in ALL_CONFIDENT_SITES.

**Comment by BinglanLi** [comment] 2023-08-02 17:27
Just to make sure I understand, @bnjvrjnke `--output-mode EMIT_ALL_CONFIDENT_SITES` followed by `bedtools intersect` gives you the **INDEL** that you were looking for?

**Comment by bnjvrjnke** [comment] 2023-08-03 02:31
Sorry for being unclear. Take the rs3064744 INDEL as example:
```
chr2	233760233	rs3064744	CAT	C,CATAT,CATATAT	.	PASS	PX=UGT1A1	GT	0/0
```
`HaplotypeCaller -L pharmcat_positions.vcf --interval-padding 20 --output-mode EMIT_ALL_CONFIDENT_SITES --emit-ref-confidence BP_RESOLUTION` will output this (slice):
```
chr2    233760233       .       C       <NON_REF>       .       .       .       GT:AD:DP:GQ:PL  0/0:34,2:36:54:0,54,1042
chr2    233760234       .       A       <NON_REF>       .       .       .       GT:AD:DP:GQ:PL  0/0:36,0:36:99:0,105,1575
chr2    233760235       .       T       <NON_REF>       .       .       .       GT:AD:DP:GQ:PL  0/0:35,1:36:70:0,70,1115
chr2    233760236       .       A       <NON_REF>       .       .       .       GT:AD:DP:GQ:PL  0/0:36,0:36:99:0,105,1575
chr2    233760237       .       T       <NON_REF>       .       .       .       GT:AD:DP:GQ:PL  0/0:34,0:34:99:0,102,1114
chr2    233760238       .       A       <NON_REF>       .       .       .       GT:AD:DP:GQ:PL  0/0:34,0:34:99:0,102,1102
chr2    233760239       .       T       <NON_REF>       .       .       .       GT:AD:DP:GQ:PL  0/0:35,0:35:99:0,105,1171
chr2    233760240       .       A       <NON_REF>       .       .       .       GT:AD:DP:GQ:PL  0/0:35,0:35:99:0,105,1140
chr2    233760241       .       T       <NON_REF>       .       .       .       GT:AD:DP:GQ:PL  0/0:35,0:35:99:0,105,1154
```
Because chr2:233760234-233760248 is callable and no ALT, I assume rs3064744 is not missing and not INDEL occur ( `-0` option). Then I convert to `ALL_CONFIDENT_SITES.bed` file, which are callable region of my sample (slice):
```
chr2    233760233       233760234       .       .       A       <NON_REF>       .       .       GT:AD:DP:GQ:PL  0/0:36,0:36:99:0,105,1575
chr2    233760234       233760235       .       .       T       <NON_REF>       .       .       GT:AD:DP:GQ:PL  0/0:35,1:36:70:0,70,1115
chr2    233760235       233760236       .       .       A       <NON_REF>       .       .       GT:AD:DP:GQ:PL  0/0:36,0:36:99:0,105,1575
chr2    233760236       233760237       .       .       T       <NON_REF>       .       .       GT:AD:DP:GQ:PL  0/0:34,0:34:99:0,102,1114
chr2    233760237       233760238       .       .       A       <NON_REF>       .       .       GT:AD:DP:GQ:PL  0/0:34,0:34:99:0,102,1102
chr2    233760238       233760239       .       .       T       <NON_REF>       .       .       GT:AD:DP:GQ:PL  0/0:35,0:35:99:0,105,1171
chr2    233760239       233760240       .       .       A       <NON_REF>       .       .       GT:AD:DP:GQ:PL  0/0:35,0:35:99:0,105,1140
chr2    233760240       233760241       .       .       T       <NON_REF>       .       .       GT:AD:DP:GQ:PL  0/0:35,0:35:99:0,105,1154
```

Lastly, using `bedtools intersect -v -a pharmcat_position.vcf -b ALL_CONFIDENT_SITES.bed` to find any no confident call site of pharmcat_position.vcf. For my sample, it return nothing, which means all PharmCAT loci are callable, so I can confidently add `-0` option in the PharmCAT pipeline: `pharmcat_pipeline -0 ${mySample}_ONLY_PASS_Variants.vcf.gz`.

**Comment by bnjvrjnke** [comment] 2023-08-03 02:32
> Just to make sure I understand, @bnjvrjnke `--output-mode EMIT_ALL_CONFIDENT_SITES` followed by `bedtools intersect` gives you the **INDEL** that you were looking for?

Sorry for being unclear. Take the rs3064744 INDEL as example:
```
chr2	233760233	rs3064744	CAT	C,CATAT,CATATAT	.	PASS	PX=UGT1A1	GT	0/0
```
`HaplotypeCaller -L pharmcat_positions.vcf --interval-padding 20 --output-mode EMIT_ALL_CONFIDENT_SITES --emit-ref-confidence BP_RESOLUTION` will output this (slice):
```
chr2    233760233       .       C       <NON_REF>       .       .       .       GT:AD:DP:GQ:PL  0/0:34,2:36:54:0,54,1042
chr2    233760234       .       A       <NON_REF>       .       .       .       GT:AD:DP:GQ:PL  0/0:36,0:36:99:0,105,1575
chr2    233760235       .       T       <NON_REF>       .       .       .       GT:AD:DP:GQ:PL  0/0:35,1:36:70:0,70,1115
chr2    233760236       .       A       <NON_REF>       .       .       .       GT:AD:DP:GQ:PL  0/0:36,0:36:99:0,105,1575
chr2    233760237       .       T       <NON_REF>       .       .       .       GT:AD:DP:GQ:PL  0/0:34,0:34:99:0,102,1114
chr2    233760238       .       A       <NON_REF>       .       .       .       GT:AD:DP:GQ:PL  0/0:34,0:34:99:0,102,1102
chr2    233760239       .       T       <NON_REF>       .       .       .       GT:AD:DP:GQ:PL  0/0:35,0:35:99:0,105,1171
chr2    233760240       .       A       <NON_REF>       .       .       .       GT:AD:DP:GQ:PL  0/0:35,0:35:99:0,105,1140
chr2    233760241       .       T       <NON_REF>       .       .       .       GT:AD:DP:GQ:PL  0/0:35,0:35:99:0,105,1154
```
Because chr2:233760234-233760248 is callable and no ALT, I assume rs3064744 is not missing and not INDEL occur ( `-0` option). Then I convert to `ALL_CONFIDENT_SITES.bed` file, which are callable region of my sample (slice):
```
chr2    233760233       233760234       .       .       A       <NON_REF>       .       .       GT:AD:DP:GQ:PL  0/0:36,0:36:99:0,105,1575
chr2    233760234       233760235       .       .       T       <NON_REF>       .       .       GT:AD:DP:GQ:PL  0/0:35,1:36:70:0,70,1115
chr2    233760235       233760236       .       .       A       <NON_REF>       .       .       GT:AD:DP:GQ:PL  0/0:36,0:36:99:0,105,1575
chr2    233760236       233760237       .       .       T       <NON_REF>       .       .       GT:AD:DP:GQ:PL  0/0:34,0:34:99:0,102,1114
chr2    233760237       233760238       .       .       A       <NON_REF>       .       .       GT:AD:DP:GQ:PL  0/0:34,0:34:99:0,102,1102
chr2    233760238       233760239       .       .       T       <NON_REF>       .       .       GT:AD:DP:GQ:PL  0/0:35,0:35:99:0,105,1171
chr2    233760239       233760240       .       .       A       <NON_REF>       .       .       GT:AD:DP:GQ:PL  0/0:35,0:35:99:0,105,1140
chr2    233760240       233760241       .       .       T       <NON_REF>       .       .       GT:AD:DP:GQ:PL  0/0:35,0:35:99:0,105,1154
```

Lastly, using `bedtools intersect -v -a pharmcat_position.vcf -b ALL_CONFIDENT_SITES.bed` to find any no confident call site of pharmcat_position.vcf. For my sample, it return nothing, which means all PharmCAT loci are callable, so I can confidently add `-0` option in the PharmCAT pipeline: `pharmcat_pipeline -0 ${mySample}_ONLY_PASS_Variants.vcf.gz`.

**Comment by moe1619** [comment] 2023-09-10 05:23
https://github.com/PharmGKB/PharmCAT/issues/135

**Comment by krukanna** [comment] 2024-02-13 09:56
I would like to reopen this issue.
I work with 30× WGS data. I am uploading a test vcf file with the positions of one NUDT15 gene and the final report in HTML format. 4 items are missing or not validated due to invalid REF or ALT. All entries required by PharmCAT for this gene are in the vcf and all are refs.
1) No indel detected in the sample, so positions chr13:48037782-48037788 are on separate lines in vcf, same for indel chr13:48040977-48040978. Why can't PharmCAT read these lines and deduce that for this indel this sample is REF respectively AGGAGTC and GA for the above mentioned indels.
Information in the html report:

> "Discarded genotype at this position because REF in VCF does not match expected reference"

2) For positions chr13:48037825 and chr13:48041103 PharmCAT expects insertions, but in my sample such insertions were not detected, so again in the vcf file these positions are REFs: C/C and T/T. Why does PharmCAT ignore this information and return warning in html:

> "Genotype at this position has no ALT allele and an indel or repeat is expected. PharmCAT cannot validate this position"


Unfortunately, I cannot use the '-0' function because the missing items are not always ref, sometimes they may be het, but for different alt allele (not important in pharmacogenomics) and then the assumption is incorrect.
It would be great if PharmCAT could deal with cases like this where the indel was not detected, but the gene has been sequenced and there is information about the REF positions in input file.
[test_vcf.zip](https://github.com/PharmGKB/PharmCAT/files/14259096/test_vcf.zip)

**Comment by krukanna** [comment] 2024-02-22 09:05
Do you have any special way, that your PharmCAT report from WGS does not contain any missing rows? Especially Indel rows
Thanks for help

**Comment by whaleyr** [comment] 2024-02-22 17:08
> Do you have any special way, that your PharmCAT report from WGS does not contain any missing rows? Especially Indel rows Thanks for help

@krukanna Can you be more specific? Do you mean variant positions showing as missing in Section III (Allele Matching Details) of the final report?

If the data is missing for PharmCAT then the data will be shown as missing since PharmCAT did not use it for making calls and we need to disclose that since it affects haplotype matching and, thus, recommendation matches.

If this is related to your previous comments let's talk about the underlying problem instead. I'm not as familiar with the intricacies of how the preprocessor handles indels so I can't answer that question directly. However, the people who _can_ answer that question will have an answer for your questions soon. Thanks for your patience.

**Comment by krukanna** [comment] 2024-02-23 07:36
Sure, thanks for response.
Mostly I care about comment from last week, I sent you also vcf file, maybe it will help to visualize the problem.

**Comment by stbiljana** [comment] 2024-07-30 13:03
Hello. Our team is currently trying to optimize PgX variant calling from various NGS data (Clinical Exomes, WES, WGS) using PharmCAT. We are having similar problems with INDEL genotype calling, our REF and ALT alleles do not match with expected in pharmcat_positions.vcf so we cannot annotate this positions elegantly (we tried using mock file but this is not very optimal solution). 
So I was wandering what is the status of this issue? Is there any progress in solving it?

**Comment by whaleyr** [comment] 2024-07-30 18:05
@stbiljana Can you give a more specific example?

PharmCAT expects REF and ALT alleles to match the GRCh38 reference assembly. Are you not able to align your sample to the reference assembly before running it through PharmCAT?

**Comment by stbiljana** [comment] 2024-07-30 20:51
The problem is the same as the @krukanna discussed.
Below are all positions that are discarded, all are indels and all are REF (we called all positions listed in pharmcat_positions.vcf from gVCF file)

```
chr10:94942205 Discarded genotype at this position because REF in VCF (C) does not match expected reference (CAATGGAAAGA)
chr10:94949161 Discarded genotype at this position because REF in VCF (A) does not match expected reference (AT)
chr10:94949281 Discarded genotype at this position because REF in VCF (G) does not match expected reference (GA)
chr19:38440747 Discarded genotype at this position because REF in VCF (C) does not match expected reference (CGAT)
chr19:38499644 Discarded genotype at this position because REF in VCF (T) does not match expected reference (TGGA)
chr19:38572266 Discarded genotype at this position because REF in VCF (T) does not match expected reference (TC)
chr19:38580039 Discarded genotype at this position because REF in VCF (T) does not match expected reference (TT)
chr1:97450065 Discarded genotype at this position because REF in VCF (T) does not match expected reference (TG)
chr1:97740410 Discarded genotype at this position because REF in VCF (G) does not match expected reference (GATGA)
chr22:42127845 Discarded genotype at this position because REF in VCF (G) does not match expected reference (GCACATCCGGATGTAGGATC)
chr22:42127962 Discarded genotype at this position because REF in VCF (T) does not match expected reference (TG)
chr22:42128198 Discarded genotype at this position because REF in VCF (C) does not match expected reference (CTCAG)
chr22:42128248 Discarded genotype at this position because REF in VCF (C) does not match expected reference (CAGTT)
chr22:42128324 Discarded genotype at this position because REF in VCF (C) does not match expected reference (CAGG)
chr22:42128795 Discarded genotype at this position because REF in VCF (A) does not match expected reference (AG)
chr22:42130727 Discarded genotype at this position because REF in VCF (A) does not match expected reference (AG)
chrX:154532055 Discarded genotype at this position because REF in VCF (C) does not match expected reference (CTCT)
chrX:154532752 Discarded genotype at this position because REF in VCF (C) does not match expected reference (CGGCCTTGCGCTCGTTCAG)
chrX:154533012 Discarded genotype at this position because REF in VCF (C) does not match expected reference (CGTGGGGTCGTCCAGGTACCCTTTG)
chrX:154534074 Discarded genotype at this position because REF in VCF (T) does not match expected reference (TCAGTGC)
chrX:154534116 Discarded genotype at this position because REF in VCF (A) does not match expected reference (ATGT)
chrX:154534414 Discarded genotype at this position because REF in VCF (G) does not match expected reference (GGGA)
chrX:154535367 Discarded genotype at this position because REF in VCF (G) does not match expected reference (GCTT)
chrX:154536021 Discarded genotype at this position because REF in VCF (C) does not match expected reference (CAGA)
chrX:154546045 Discarded genotype at this position because REF in VCF (C) does not match expected reference (CATG)
```

We have used GRCh38 reference assembly, pipeline is constructed according to the GATK best practices, and referent genome is from their cloud bucket.

**Comment by whaleyr** [comment] 2024-07-30 21:01
Thanks, that makes the situation much clearer.

**Comment by moe1619** [comment] 2024-08-05 16:00
Hello,

Can you clarify your alignment and variant calling pipeline which leads to the correct indel representation? Do you still use https://github.com/PharmGKB/pgkb-ngs-pipeline/tree/master ?

Thanks

**Comment by moe1619** [comment] 2024-08-05 19:24
I have opened a question on GATK. Hopefully I've captured at least some of our issues.

https://gatk.broadinstitute.org/hc/en-us/community/posts/28014911596187-Force-genotype-with-specific-reference-allele-combinations

**Comment by markwoon** [comment] 2024-08-05 21:24
The [https://github.com/PharmGKB/pgkb-ngs-pipeline](https://github.com/PharmGKB/pgkb-ngs-pipeline/tree/master) is no longer in use.

**Comment by moe1619** [comment] 2024-08-05 22:33
Thanks very much. Do you use a specific pipeline which generates a VCF to your specs? Thanks!

**Comment by whaleyr** [comment] 2024-08-05 22:34
I suggest checking out the [VCF Preprocessor](https://pharmcat.org/using/VCF-Preprocessor/) that's built into PharmCAT.

**Comment by moe1619** [comment] 2024-08-06 14:34
I used the following series of commands to get appropriately formatted output for pharmcat starting with a CRAM and using haplotypecaller. I would consider updating the suggested haplotypecaller command in the pharmcat website vcf requirement section to reflect the command below.

# the addition of --alleles and --max-mnp-distance 1 made a huge difference
$gatk_path --java-options "-Xmx4G" HaplotypeCaller -R $reference_grch38 \
    --alleles $pharmcat_git/pharmcat_positions.vcf \
    -I $bam_path \
    -O $vcf_single_sample \
    -L $pharmcat_git/pharmcat_positions.vcf \
    -ip 25 \
    --max-mnp-distance 1 \
    --output-mode EMIT_ALL_ACTIVE_SITES

# the following is necessary because the preprocessor breaks if the quality is not a number and the quality for some of the calls in the vcf is "Infinity"
  cat ${vcf_single_sample} | sed 's/\tInfinity/\t1000/' > $single_sample_inf_removed_gt_vcf

 python3 $pharmcat_git/preprocessor/pharmcat_vcf_preprocessor.py -vcf \
    $single_sample_inf_removed_gt_vcf -o $single_sample_output_folder -bf \
    $sample_internal_name -k -v \
    -refVcf $pharmcat_git/pharmcat_positions.vcf.bgz \
    -refFna $pharmcat_git/bin/reference.fna.bgz -ss

java -jar $pharmcat_path -vcf $preprocessed_gz_vcf -o $single_sample_output_folder -bf $sample_internal_name -reporterJson

**Comment by moe1619** [comment] 2024-08-06 14:51
For exomes, consider

$gatk_path --java-options "-Xmx4G"  SelectVariants  \
   -V $vcf_single_sample_pre_filter \
   -O $vcf_single_sample \
    --exclude-filtered

to get rid of missing positions. OK, I think thats all I got. Thanks.
